### ISSUE TITLE
asymmetric  problem

### ISSUE THREAD

**Issue by WKKO** [LucasNolasco/DeepDFML-NILM#4]
I'm sorry to bother you. After reading your paper, I have a little question. Why is the current in this picture asymmetric on the positive and negative half axes, and the gap is very large? What is the reason for this situation? If you have time, I hope you can give me a reply。

![1](https://user-images.githubusercontent.com/102801456/222071510-8fe21313-0dc8-4272-b23d-d8e02810c682.PNG)

**Comment by LucasNolasco** [comment]
Don't worry! I hope my work is being helpful to you :D

Regarding your question, it's an interesting observation, but that's not something we did intentionally. It happens because of appliance 23's (Hair dryer Super) behavior. Its current consumption curve is quite asymmetric, as you pointed out. And it also requires way more power than the other appliances in the waveform of this figure, so it's hard to see the negative contribution of the other appliances connected after. 

However, the signal is almost symmetric if you check that portion of the signal after appliance 23 is turned off the first time and before it's turned on again. So, it's not something from our work but merely the behavior of the database (LIT-Dataset).

Here is a waveform acquired using only the Hair dryer Super (appliance 23):

![appliance23](https://user-images.githubusercontent.com/13191527/222931909-9091baee-3f8c-4430-8443-a3dc851cb181.jpg)

**Comment by WKKO** [comment]
Thank you very much for answering my question, which has solved my long-standing problems. In fact, I want to classify the load based on UK_DALE recently, and the high-frequency total current waveform in it is also asymmetrical, as shown below. I think this can be explained for the same reason. Finally, thank you very much for your help and wish you all the best.
![image](https://user-images.githubusercontent.com/102801456/222958441-33f4d158-773b-4def-9f96-88b42775c98d.png)
